name: UI-Shared
version: '${project.version}'
description: 'Shared utilities: structures, recipes, magnet, radiation, lightning'
main: com.ultimateimprovments.shared.UIShared
api-version: '26.3'
author: rizer001
dependencies:
  server:
    UI-Core:
      load: BEFORE
      required: true
      join-classpath: true
