package com.ultimateimprovments.core;

import com.ultimateimprovments.config.AddonConfigManager;
import com.ultimateimprovments.config.CompositeConfig;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.logging.Filter;
import java.util.logging.LogRecord;
import java.util.logging.Logger;

/**
 * Main — entry point of UltimateImprovments.
 * <p>
 * Data layout: the whole UI-* family shares ONE data folder
 * ({@code plugins/UltimateImprovments}, see {@link UltimateDirs}) and ONE SQLite
 * database. Configuration lives in per-addon TOML files
 * ({@code configs/UI-<Addon>.toml}, see {@link AddonConfigManager}); every file
 * contains the addon's settings and its RU/EN messages.
 * <p>
 * {@code getConfig()} returns a {@link CompositeConfig} that routes reads/writes to
 * the owning addon's file by first path segment, so every existing call site keeps
 * working unchanged.
 */
public class Main extends JavaPlugin {

    private static Main instance;
    private Filter originalLogFilter;

    /** Composite view over all per-addon configs. */
    private volatile CompositeConfig composite;

    public static Main getInstance() {
        return instance;
    }

    public java.io.File getPluginFile() {
        return getFile();
    }

    // NOTE: JavaPlugin.getDataFolder() is final and cannot be overridden. The
    // shared family folder is resolved explicitly through {@link UltimateDirs}
    // (database, configs, logs, loose files) — see the call sites in
    // DatabaseManager, AddonConfigManager and the addon data files.

    // ========================================================================
    // COMPOSITE CONFIG BACKEND (per-addon TOML files)
    // ========================================================================

    @Override
    public FileConfiguration getConfig() {
        CompositeConfig cfg = composite;
        if (cfg == null) {
            reloadConfig();
            cfg = composite;
        }
        return cfg != null ? cfg : super.getConfig();
    }

    @Override
    public void reloadConfig() {
        UltimateDirs.migrateLegacyFolders();
        AddonConfigManager.init();
        this.composite = new CompositeConfig();
    }

    @Override
    public void saveConfig() {
        AddonConfigManager.saveAll();
    }

    @Override
    public void saveDefaultConfig() {
        // Per-addon files are generated by AddonConfigManager.init(). Nothing to do.
    }

    @Override
    public void onEnable() {
        instance = this;

        // Suppress Paper's 'Fatal error trying to convert...' — this message
        // is printed by Paper for EVERY class with an unsupported Java version
        // and carries no useful information (cannot be fixed, only by updating Java).
        suppressPaperConversionErrors();

        new PluginStartup(this).startupPlugin();
    }

    @Override
    public void onDisable() {
        // Restore the original filter on shutdown
        if (originalLogFilter != null) {
            getLogger().setFilter(originalLogFilter);
        }
        new PluginShutdown(this).shutdownPlugin();
    }

    /**
     * Sets a filter on the plugin logger, suppressing
     * Paper messages about incompatible class file versions.
     */
    private void suppressPaperConversionErrors() {
        Logger logger = getLogger();
        originalLogFilter = logger.getFilter();
        logger.setFilter(new Filter() {
            @Override
            public boolean isLoggable(LogRecord record) {
                if (record == null || record.getMessage() == null) return true;
                String msg = record.getMessage();
                if (msg.contains("Fatal error trying to convert")) return false;
                if (msg.contains("Unsupported class file major version")) return false;
                return true;
            }
        });
    }
}
