radiation:
  enabled: true
  natural_decay: 1
  effects_enabled: true
  ancient_debris_radiation: 2
  basalt_deltas_radiation: 2
  end_radiation: 2
  lead_shield_reduction: 2
  antirad_reduction: 100
  kill_reduction: 100
  death_reset: true
  mace_use_radiation: 50
  trident_use_radiation: 50
  elytra_use_radiation: 50
  reactor_core_radiation: 10
  reactor_pressure_radiation: 600
  reactor_meltdown_close: 6400
  reactor_meltdown_far: 3200
  space_radiation: 199
  space_interval_ticks: 200
  dosimeter_ms_per_unit: 1.0
space:
  enabled: true
  debug: false
  teleport_cooldown_ticks: 100
  rocket_launch_delay_ticks: 60
  gravity: 0.01
  oxygen_damage_per_second: 1
  meteor_space_only: true
  space_entry_worlds:
  - world
