name: UI-Protection
version: ${project.version}
description: UltimateImprovments — block protection + void protection add-on
main: com.ultimateimprovments.core.UIProtection
api-version: '26.2'
author: rizer001
addon-for: UI-Core
depend: [UI-Core, UI-Shared]
