name: UI-Datapack
version: '${project.version}'
description: UltimateImprovments — bundled datapack installer
main: com.ultimateimprovments.datapack.UIDatapack
api-version: '26.2'
author: rizer001
dependencies:
  server:
    UI-Core:
      load: BEFORE
      required: true
      join-classpath: true
