name: UI-Essentials
version: '${project.version}'
description: 'Essential commands: home, teleport, heal, reports, NBT editor, and more'
main: com.ultimateimprovments.module.UIEssentials
api-version: '26.3'
author: rizer001
dependencies:
  server:
    UI-Core:
      load: BEFORE
      required: true
      join-classpath: true
