name: UI-Anticheat
version: '${project.version}'
description: 'Advanced anti-cheat system for UltimateImprovements'
main: com.ultimateimprovments.module.UIAntiCheat
api-version: '26.2'
author: rizer001
dependencies:
  server:
    UI-Core:
      load: BEFORE
      required: true
      join-classpath: true
