name: UI-Combat
version: '${project.version}'
description: 'Weapons, turrets, and projectile system'
main: com.ultimateimprovments.combat.UICombat
api-version: '26.2'
author: rizer001
dependencies:
  server:
    UI-Core:
      load: BEFORE
      required: true
      join-classpath: true
