name: UI-Admin
version: '${project.version}'
description: UltimateImprovments — economy, op management and updater add-on
main: com.ultimateimprovments.core.UIAdmin
api-version: '26.3'
author: rizer001
dependencies:
  server:
    UI-Core:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      required: false
      join-classpath: true
    PlaceholderAPI:
      required: false
      join-classpath: true
    LuckPerms:
      required: false
      join-classpath: true
